### ISSUE TITLE
Latest jamm reference in cassandra-env.sh.erb breaks older C* version installs

### ISSUE THREAD

**Issue by amorcomb** [target/dse-cookbook#23]
Running dse version "4.6.2-1" which installs jamm-0.2.5.jar. 

Cassandra cannot start because the jamm.jar referenced in the cassandra-env.sh (0.3.0) doesn't exist. 

Can this be overwritten with a custom jamm_version attribute? Should be a simple enough fix. Thanks for maintaining this cookbook.

**Comment by dcparker88** [comment]
good idea, I will look in to adding that.

**Comment by dcparker88** [comment]
how does #24 look?

**Comment by amorcomb** [comment]
Exactly what was needed. Should provide greater flexibility handling mismatched jamm / C* releases in the future.

**Comment by dcparker88** [comment]
perfect - let me know if you need anything else.
