### ISSUE TITLE
Icrease the version please

### ISSUE THREAD

**Issue by blagoygenadiev-taulia** [target/dse-cookbook#25]
Hi, 

It's really great that you have added a templates for DSE version 4.7.0-1 but could you please also increase the cookbook version so the chef client can see them?
Thank you in advance.

Regards,
Blagoy

**Comment by dcparker88** [comment]
I uploaded the latest version of the cookbook to supermarket, let me know if you have any issues

**Comment by blagoygenadiev-taulia** [comment]
It's ok, thank you!
