### ISSUE TITLE
timeout values in cassandra.yaml are not configurable for the most part

### ISSUE THREAD

**Issue by amorcomb** [target/dse-cookbook#27]
This block in cassandra.yaml doesn't use attributes to set its values (except one) which makes it impossible to configure without rolling your own cassandra.yaml.erb. 

# How long the coordinator should wait for read operations to complete
read_request_timeout_in_ms: 10000
# How long the coordinator should wait for seq or index scans to complete
range_request_timeout_in_ms: <%= node['cassandra']['range_request_timeout_in_ms'] %> # 10000
# How long the coordinator should wait for writes to complete
write_request_timeout_in_ms: 10000
# How long a coordinator should continue to retry a CAS operation
# that contends with other proposals for the same row
cas_contention_timeout_in_ms: 1000
# How long the coordinator should wait for truncates to complete
# (This can be much longer, because unless auto_snapshot is disabled
# we need to flush first so we can snapshot before removing the data.)
truncate_request_timeout_in_ms: 60000
# The default timeout for other, miscellaneous operations
request_timeout_in_ms: 10000

It would be an improvement to parameterize these values.

**Comment by dcparker88** [comment]
you're right, that would definitely make this more flexible. I will look in to getting a quick PR

**Comment by dcparker88** [comment]
see #28

**Comment by amorcomb** [comment]
Thanks for the update.
