### ISSUE TITLE
Recommendation for upgrading from DSE 4.7 to 5.0?

### ISSUE THREAD

**Issue by kbruner** [target/dse-cookbook#67]
We're using this cookbook to manage our DSE Cassandra rings, which are currently running 4.7.  Has anyone tested trying a version upgrade directly via the cookbook by chaging the `dse_version`?  [This doc](https://docs.datastax.com/en/upgrade/doc/upgrade/datastax_enterprise/upgdDSE50.html) supports the direct 4.7->5.0 upgrade path, but shows a lot of manual, per-node interim steps.

**Comment by dcparker88** [comment]
I personally haven't done these version upgrades, but in the past I used chef to install the new version of dse, but still followed the manual steps.  The most important piece is usually the upgradesstables, which from experience can take down a cluster if you run it everywhere at once :| I would say do them one at a time and make sure it works.

**Comment by kbruner** [comment]
Ok, thanks for the input.  That's what I figured.  Our rings are small enough that manual is still a viable option, but for larger rings, that could be painful.
